use axum::Router;
use axum::routing::{get, post, delete};
use std::sync::Arc;
use crate::api::{handlers, openapi, websocket, AppState};
use utoipa::OpenApi;

pub fn api_routes() -> Router<Arc<AppState>> {
    Router::new()
        // OpenAPI / Swagger UI
        .route("/api-docs/openapi.json", get(|| async { axum::Json(openapi::ApiDoc::openapi()) }))
        
        // Public routes (no auth required)
        .route("/api/health", get(handlers::health))
        .route("/api/auth/login", post(handlers::login))
        // Security routes (protected)
        .route("/api/auth/logout", post(handlers::logout))
        .route("/api/auth/change-password", post(handlers::change_password))
        .route("/api/security/audit-logs", get(handlers::get_audit_logs))
        .route("/api/security/status", get(handlers::get_security_status))
        // Protected routes
        .route("/api/config", get(handlers::get_config))
        .route("/api/config/save", post(handlers::save_config))
        .route("/api/interfaces", get(handlers::get_interfaces))
        .route("/api/interfaces/:name/up", post(handlers::iface_up))
        .route("/api/interfaces/:name/down", post(handlers::iface_down))
        .route("/api/interfaces/:name/config", post(handlers::configure_interface))
        .route("/api/interfaces/:name/stats", get(handlers::get_interface_stats))
        .route("/api/interfaces/bind", post(handlers::bind_interface))
        .route("/api/interfaces/unbind", post(handlers::unbind_interface))
        .route("/api/interfaces/bound", get(handlers::list_bound_interfaces))
        .route("/api/interfaces/:name/configure-bound", post(handlers::configure_bound_interface))
        .route("/api/pppoe/clients", get(handlers::get_pppoe_clients))
        .route("/api/pppoe/status", get(handlers::get_pppoe_status))
        .route("/api/pppoe/create", post(handlers::create_pppoe_client))
        // PPPoE auto-connect
        .route("/api/pppoe/autoconnect/start", post(handlers::start_pppoe_autoconnect))
        .route("/api/pppoe/autoconnect/stop", post(handlers::stop_pppoe_autoconnect))
        .route("/api/pppoe/autoconnect/status", get(handlers::get_pppoe_autoconnect_status))
        .route("/api/pppoe/autoconnect/config", post(handlers::configure_pppoe_autoconnect))
        .route("/api/nat/status", get(handlers::get_nat_status))
        .route("/api/nat/enable", post(handlers::enable_nat))
        .route("/api/dhcp/status", get(handlers::get_dhcp_status))
        .route("/api/dhcp/enable", post(handlers::enable_dhcp))
        .route("/api/dhcp/disable", post(handlers::disable_dhcp))
        .route("/api/dns/status", get(handlers::get_dns_status))
        .route("/api/dns/enable", post(handlers::enable_dns))
        .route("/api/dns/disable", post(handlers::disable_dns))
        .route("/api/dns/cache/clear", post(handlers::clear_dns_cache))
        .route("/api/dns/cache/stats", get(handlers::get_dns_cache_stats))
        .route("/api/routes", get(handlers::get_routes))
        .route("/api/system", get(handlers::get_system_status))
        .route("/api/system/vpp-performance", get(handlers::get_vpp_performance))
        .route("/api/config/status", get(handlers::get_config_status))
        // FRRouting
        .route("/api/frr/status", get(handlers::get_frr_status))
        .route("/api/frr/routes", get(handlers::get_frr_routes))
        .route("/api/frr/add-route", post(handlers::add_frr_route))
        .route("/api/frr/del-route", post(handlers::del_frr_route))
        // IPv6
        .route("/api/ipv6/status", get(handlers::get_ipv6_status))
        .route("/api/ipv6/neighbors", get(handlers::get_ipv6_neighbors))
        .route("/api/dhcpv6/status", get(handlers::get_dhcpv6_status))
        // Log management
        .route("/api/logs", post(handlers::get_logs))
        .route("/api/logs/clear", post(handlers::clear_logs))
        // Firewall management
        .route("/api/firewall/status", get(handlers::get_firewall_status))
        .route("/api/firewall/add-rule", post(handlers::add_firewall_rule))
        .route("/api/firewall/update-rule", post(handlers::update_firewall_rule))
        .route("/api/firewall/del-rule", post(handlers::delete_firewall_rule))
        .route("/api/firewall/reorder", post(handlers::reorder_firewall_rules))
        .route("/api/firewall/enable", post(handlers::enable_firewall))
        .route("/api/firewall/disable", post(handlers::disable_firewall))
        // Firewall groups
        .route("/api/firewall/groups", get(handlers::list_firewall_groups))
        .route("/api/firewall/groups/add", post(handlers::add_firewall_group))
        .route("/api/firewall/groups/:name/delete", post(handlers::delete_firewall_group))
        .route("/api/firewall/groups/:name/add-rule", post(handlers::add_rule_to_group))
        .route("/api/firewall/groups/:name/remove-rule", post(handlers::remove_rule_from_group))
        // Firewall aliases
        .route("/api/firewall/aliases", get(handlers::list_firewall_aliases))
        .route("/api/firewall/aliases/add", post(handlers::add_firewall_alias))
        .route("/api/firewall/aliases/:name", post(handlers::update_firewall_alias))
        .route("/api/firewall/aliases/:name/delete", post(handlers::delete_firewall_alias))
        .route("/api/firewall/aliases/:name/refresh", post(handlers::refresh_firewall_alias))
        // Firewall schedules
        .route("/api/firewall/schedules", get(handlers::list_firewall_schedules))
        .route("/api/firewall/schedules/add", post(handlers::add_firewall_schedule))
        .route("/api/firewall/schedules/:name/delete", post(handlers::delete_firewall_schedule))
        // GeoIP
        .route("/api/firewall/geoip", post(handlers::update_firewall_geoip))
        // Traffic shaper (firewall-integrated)
        .route("/api/firewall/shaper/status", get(handlers::get_shaper_status))
        .route("/api/firewall/shaper/interface", post(handlers::set_shaper_interface))
        .route("/api/firewall/shaper/interface/:name/delete", post(handlers::remove_shaper_interface))
        .route("/api/firewall/shaper/queue", post(handlers::add_shaper_queue))
        .route("/api/firewall/shaper/queue/:name/delete", post(handlers::delete_shaper_queue))
        // IDS / Suricata
        .route("/api/firewall/ids/config", post(handlers::update_ids_config))
        .route("/api/firewall/ids/alerts", get(handlers::get_ids_alerts))
        .route("/api/firewall/ids/alerts/clear", post(handlers::clear_ids_alerts))
        .route("/api/firewall/ids/stats", get(handlers::get_ids_stats))
        // QoS management
        .route("/api/qos/status", get(handlers::get_qos_status))
        .route("/api/qos/policer", post(handlers::create_policer))
        .route("/api/qos/policer/:name", delete(handlers::delete_policer))
        .route("/api/qos/interface/:name/limit", post(handlers::set_interface_rate_limit))
        // Flow monitoring
        .route("/api/flows/status", get(handlers::get_flow_status))
        .route("/api/flows/top", get(handlers::get_flow_top))
        .route("/api/flows/export", post(handlers::set_flow_export))
        .route("/api/flows/export/enable", post(handlers::enable_flow_export))
        .route("/api/flows/export/disable", post(handlers::disable_flow_export))
        .route("/api/flows/classify-setup", post(handlers::setup_flow_classify))
        .route("/api/flows/list", get(handlers::list_flows))
        // Connection tracking
        .route("/api/conntrack/status", get(handlers::get_conntrack_status))
        .route("/api/conntrack/connections", get(handlers::get_conntrack_connections))
        .route("/api/conntrack/stats", get(handlers::get_conntrack_stats))
        .route("/api/conntrack/top", get(handlers::get_conntrack_top))
        .route("/api/conntrack/filter", post(handlers::filter_conntrack_connections))
        .route("/api/conntrack/detail", get(handlers::get_conntrack_detail))
        // Traffic control
        .route("/api/traffic/status", get(handlers::get_traffic_status))
        .route("/api/traffic/limit", post(handlers::set_traffic_limit))
        .route("/api/traffic/limit/interface/:iface", delete(handlers::remove_traffic_interface_limit))
        .route("/api/traffic/limit/ip/:ip", delete(handlers::remove_traffic_ip_limit))
        .route("/api/traffic/priority", post(handlers::set_traffic_priority))
        .route("/api/traffic/app-class", post(handlers::set_traffic_app_class))
        .route("/api/traffic/app-class/:name", delete(handlers::remove_traffic_app_class))
        .route("/api/traffic/defaults", post(handlers::load_traffic_defaults))
        .route("/api/traffic/stats", get(handlers::get_traffic_stats))
        .route("/api/traffic/reset", post(handlers::reset_traffic))
        // VPN management
        .route("/api/vpn/status", get(handlers::get_vpn_status))
        .route("/api/vpn/connections", get(handlers::get_vpn_connections))
        .route("/api/vpn/wireguard/config", post(handlers::configure_wireguard))
        .route("/api/vpn/ipsec/config", post(handlers::configure_ipsec))
        .route("/api/vpn/openvpn/config", post(handlers::configure_openvpn))
        .route("/api/vpn/down", post(handlers::vpn_down))
        // Network diagnostics
        .route("/api/diag/status", get(handlers::get_diag_status))
        .route("/api/diag/ping", post(handlers::diag_ping))
        .route("/api/diag/traceroute", post(handlers::diag_traceroute))
        .route("/api/diag/dns", post(handlers::diag_dns))
        .route("/api/diag/portscan", post(handlers::diag_portscan))
        // VyOS-style configuration management
        .route("/api/config/tree", get(handlers::get_config_tree))
        .route("/api/config/staging", get(handlers::get_config_staging))
        .route("/api/config/set", post(handlers::config_set_value))
        .route("/api/config/delete", post(handlers::config_delete_value))
        .route("/api/config/commit", post(handlers::config_commit))
        .route("/api/config/rollback/:version", post(handlers::config_rollback))
        .route("/api/config/discard", post(handlers::config_discard))
        .route("/api/config/diff", get(handlers::config_diff))
        .route("/api/config/diff/:v1/:v2", get(handlers::config_diff_versions))
        .route("/api/config/history", get(handlers::config_history))
        .route("/api/config/templates", get(handlers::config_list_templates))
        .route("/api/config/template/save", post(handlers::config_save_template))
        .route("/api/config/template/apply", post(handlers::config_apply_template))
        .route("/api/config/cli/session", post(handlers::config_cli_session))
        .route("/api/config/cli/execute", post(handlers::config_cli_execute))
        // Config Import/Export
        .route("/api/config/export", get(handlers::config_export))
        .route("/api/config/import", post(handlers::config_import))
        .route("/api/config/validate", post(handlers::config_validate))
        .route("/api/config/import/history", get(handlers::config_import_history))
        // Service Manager
        .route("/api/services", get(handlers::list_services))
        .route("/api/services/:name/status", get(handlers::get_service_status))
        .route("/api/services/:name/start", post(handlers::start_service))
        .route("/api/services/:name/stop", post(handlers::stop_service))
        .route("/api/services/:name/restart", post(handlers::restart_service))
        .route("/api/services/:name/reload", post(handlers::reload_service))
        // Monitoring
        .route("/api/monitor/metrics", get(handlers::get_monitor_metrics))
        .route("/api/monitor/history", get(handlers::get_monitor_history))
        .route("/api/monitor/alerts", get(handlers::get_monitor_alerts))
        .route("/api/monitor/alerts/ack", post(handlers::acknowledge_alert))
        // VPP ACL (direct VPP integration)
        .route("/api/vpp/acl/add", post(handlers::add_vpp_acl))
        .route("/api/vpp/acl/list", get(handlers::list_vpp_acls))
        .route("/api/vpp/acl/:index", delete(handlers::delete_vpp_acl))
        .route("/api/vpp/acl/apply", post(handlers::apply_vpp_acl))
        // WebSocket for real-time updates
        .route("/ws", get(websocket::ws_handler))
}
